name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
        
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v26.1

      - name: Check protected file not changed
        run: |
          changed_protected=0
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo $file
            if [[ "$file" =~ ^protected* ]]; then
              changed_protected=1
            fi
          done
          if [ $changed_protected -eq 1 ]; then
            exit 1
          fi
