name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v26.1

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.changed_files }}; do
            echo "$file was changed"
          done
